### ISSUE TITLE
Error in pdu reader, with alpha number

### ISSUE THREAD

**Issue by menemy** [faucamp/python-gsmmodem#36]
Sms to confirm

07919762020033F1400DD0CDF2396C7EBB010008415072411084618C0500035602010053004D005300200063006F00640065003A00200034003800350036002C00200063006F006E006600690072006D006100740069006F006E0020006F00660020006100730073006F00630069006100740069006F006E0020006200650074007700650065006E0020006100630063006F0075006E007400200061006E00640020004D00650067

Get error "ValueError: unconverted data remains: 01" since last alpha of number goes to time field

python-gsmmodem==0.9

**Comment by faucamp** [comment]
Thanks for the report! This issue has been fixed in df20a9a2960883fbb454bc73c8c5a13f044ef8d4. If the issue persists, feel free to re-open this issue. I will publish a new version of python-gsmmodem with the fix to pypi tomorrow.

**Comment by menemy** [comment]
Thank you very much.
Everything works fine now.
