### ISSUE TITLE
Timeout for CPIN command may be too short?

### ISSUE THREAD

**Issue by MaplerStory** [faucamp/python-gsmmodem#50]
the timeout for CPIN command is 0.25
`cpinResponse = lineStartingWith('+CPIN', self.write('AT+CPIN?', timeout=0.25))`
it's very easy to raise TimeoutException.
and many other command use the default timeout (timeout=5), 
so why this command use such a short timeout? dose it mean to?

**Comment by babca** [comment]
The timeout was probably too short.
Your issue should be resolved, see: https://github.com/babca/python-gsmmodem/issues/11

**Comment by MaplerStory** [comment]
yeah, that's good~~ :+1:
