### ISSUE TITLE
unread sms on startup

### ISSUE THREAD

**Issue by dauheeIRL** [faucamp/python-gsmmodem#7]
Hi,

Just in case you weren't busy enough, I had an idea for a feature request on connect() - call something like:
AT+CMGL="REC UNREAD"
and read all SMS that has been sent while the application was not running. When finished this, can then delete all read SMS like following (or just do each singularly):
AT+CMGD=1,1
That way the modem memory will not fill up with unread messages if using the application over time, and users can get messages that were sent prior to the app running, which could be handy.

Just an idea anyhow, not sure how easy/hard it would be to implement.

Best regards,

David.

**Comment by faucamp** [comment]
I'll look into this - was thinking of doing something similar. It will most probably end up as a separate method (and not part of connect().

**Comment by faucamp** [comment]
This functionality is now fully implemented as of cc9288b7b8189e709e27a15618fdb9b946b82d3b. Call `processStoredSms()` after `connect()` to process any locally-stored received SMS messages in the same way the GsmModem class would normally handle them.
